LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := DouYin
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_PATH := $(TARGET_OUT_ODM)/bundled_uninstall_back-app
LOCAL_SRC_FILES := $(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_ENFORCE_USES_LIBRARIES := false
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_JNI_SHARED_LIBRARIES_ABI := arm
MY_LOCAL_PREBUILT_JNI_LIBS := \
	lib/arm/libAGFX.so\
	lib/arm/libByteVC1_dec.so\
	lib/arm/libCKResourceJni.so\
	lib/arm/libCoreCpt.so\
	lib/arm/libCtaApiLib.so\
	lib/arm/libCurve25519Donna.so\
	lib/arm/libCutSameConsumerJni.so\
	lib/arm/libCutSameJni.so\
	lib/arm/libDavinciResourceJni.so\
	lib/arm/libEffectEditorABTestJni.so\
	lib/arm/libEffectEditorJni.so\
	lib/arm/libEncryptor.so\
	lib/arm/libExtractorJni.so\
	lib/arm/libIESLiveStreamSDK.so\
	lib/arm/libILAMaterialSDK.so\
	lib/arm/libILASDK.so\
	lib/arm/libLogTransport.so\
	lib/arm/libMediaDelegatesJni.so\
	lib/arm/libNLEEditorJni.so\
	lib/arm/libNLEMediaJni.so\
	lib/arm/libNLEMediaPublicJni.so\
	lib/arm/libNLEMediaRemoteJni.so\
	lib/arm/libNLEPresetJni.so\
	lib/arm/libNLEResourcesDAVJni.so\
	lib/arm/libNLETemplateModelJni.so\
	lib/arm/libRealX.so\
	lib/arm/libRealXAudio.so\
	lib/arm/libRealXBase.so\
	lib/arm/libSmartScanJni.so\
	lib/arm/libTTHtmlParser_dyreader.so\
	lib/arm/libTTMachineCore.so\
	lib/arm/libTTWebViewSdkFlipped.so\
	lib/arm/libTuringYuvUtils.so\
	lib/arm/libabrmodule.so\
	lib/arm/libalog.so\
	lib/arm/libanimax.so\
	lib/arm/libapplog_rust.so\
	lib/arm/libarcore_sdk_c.so\
	lib/arm/libarcore_sdk_jni.so\
	lib/arm/libart_sym.so\
	lib/arm/libaudio_fingerprint_sdk.so\
	lib/arm/libaudioeffect.so\
	lib/arm/libaudioeffectdls.so\
	lib/arm/libavframework.so\
	lib/arm/libavmdlbase.so\
	lib/arm/libavmdlv2.so\
	lib/arm/libbach-sdk-jni.so\
	lib/arm/libbat.so\
	lib/arm/libbdheif.so\
	lib/arm/libbdmpg123.so\
	lib/arm/libbdsword.so\
	lib/arm/libbdvideouploader.so\
	lib/arm/libbdzstd.so\
	lib/arm/libbmf_hydra_lite.so\
	lib/arm/libbrotlicommon.so\
	lib/arm/libbrotlidec.so\
	lib/arm/libbspatch.so\
	lib/arm/libbtch_collection.so\
	lib/arm/libbuffer.so\
	lib/arm/libbvcparser.so\
	lib/arm/libbyteVC2dec.so\
	lib/arm/libbyte_coffee.so\
	lib/arm/libbyte_rec.so\
	lib/arm/libbyteaudio.so\
	lib/arm/libbytebench.so\
	lib/arm/libbytehook.so\
	lib/arm/libbytelink.so\
	lib/arm/libbytemonitor.so\
	lib/arm/libbytenn.so\
	lib/arm/libbytenn_plugin_ocl.so\
	lib/arm/libbytennllm-jni.so\
	lib/arm/libbytennllm.so\
	lib/arm/libbytennwrapper.so\
	lib/arm/libbytertc_nico_extension.so\
	lib/arm/libbytevc0.so\
	lib/arm/libbytevc1enc.so\
	lib/arm/libc++_shared.so\
	lib/arm/libcachemodule.so\
	lib/arm/libcastproxy.so\
	lib/arm/libchannel.so\
	lib/arm/libcjtfccsm.so\
	lib/arm/libcoversong_sdk.so\
	lib/arm/libcovode_number.so\
	lib/arm/libcvt.so\
	lib/arm/libdaemon.so\
	lib/arm/libdelta.so\
	lib/arm/libdisktracing.so\
	lib/arm/libec_jpeg_decoder.so\
	lib/arm/libedgeai.so\
	lib/arm/libeffect.so\
	lib/arm/liberis-analyzer.so\
	lib/arm/liberis.so\
	lib/arm/libevil-core.so\
	lib/arm/libfastcv.so\
	lib/arm/libfastmalloc.so\
	lib/arm/libfdk-aac.so\
	lib/arm/libfdtracker.so\
	lib/arm/libfileprotect.so\
	lib/arm/libflipped.so\
	lib/arm/libflock-lib.so\
	lib/arm/libgaia_lib.so\
	lib/arm/libgecko_encrypt.so\
	lib/arm/libgeckox_bspatch.so\
	lib/arm/libgifimage.so\
	lib/arm/libgkfs.so\
	lib/arm/libgodzilla-sysopt.so\
	lib/arm/libhdiffpatch.so\
	lib/arm/libhelios_bm.so\
	lib/arm/libhidden_watermark_lib.so\
	lib/arm/libhpatchz.so\
	lib/arm/libiesapplogger.so\
	lib/arm/libimagepipeline.so\
	lib/arm/libinterstellar.so\
	lib/arm/libiorap.so\
	lib/arm/libisecgm.so\
	lib/arm/libjarvis-binder.so\
	lib/arm/libjarvis-experience-metric.so\
	lib/arm/libjarvis-stacktrace.so\
	lib/arm/libjarvis-trace.so\
	lib/arm/libjato.so\
	lib/arm/libjazz.so\
	lib/arm/libjstack.so\
	lib/arm/libkeva.so\
	lib/arm/libkrypton.so\
	lib/arm/libkrypton_sar.so\
	lib/arm/libkryptonaudioeffect.so\
	lib/arm/libkryptonaurum.so\
	lib/arm/libkryptoneffect.so\
	lib/arm/libkryptoni18n.so\
	lib/arm/libkryptonrtc.so\
	lib/arm/libkryptonvecamera.so\
	lib/arm/liblens.so\
	lib/arm/libliveffect.so\
	lib/arm/libliveplayer.so\
	lib/arm/liblivestrategy.so\
	lib/arm/liblogger.so\
	lib/arm/liblynx.so\
	lib/arm/liblynx_helium.so\
	lib/arm/liblynx_krypton.so\
	lib/arm/liblynx_markdown.so\
	lib/arm/liblynx_v8_bridge.so\
	lib/arm/liblynxservice.so\
	lib/arm/liblynxtrace.so\
	lib/arm/libmannorarmor.so\
	lib/arm/libmemorydegradation.so\
	lib/arm/libmetasec_ml.so\
	lib/arm/libmethod_discover.so\
	lib/arm/libmonitorcollector-lib.so\
	lib/arm/libmotion.so\
	lib/arm/libmotion_compress.so\
	lib/arm/libnapi.so\
	lib/arm/libnative-filters.so\
	lib/arm/libnative_classloader.so\
	lib/arm/libnative_log.so\
	lib/arm/libnativeaudio.so\
	lib/arm/libnativebuffer.so\
	lib/arm/libnativelog.so\
	lib/arm/libnativeserver.so\
	lib/arm/libnetecho.so\
	lib/arm/libnetworkpredictor.so\
	lib/arm/libnewep.so\
	lib/arm/libnleimagejni.so\
	lib/arm/libnpth.so\
	lib/arm/libnpth_bt.so\
	lib/arm/libnpth_dl.so\
	lib/arm/libnpth_dumper.so\
	lib/arm/libnpth_fd_tracker.so\
	lib/arm/libnpth_heap_tracker.so\
	lib/arm/libnpth_logcat.so\
	lib/arm/libnpth_ref_monitor.so\
	lib/arm/libnpth_repair.so\
	lib/arm/libnpth_tls_monitor.so\
	lib/arm/libnpth_unw.so\
	lib/arm/libnpth_unwind.so\
	lib/arm/libnpth_vm_monitor.so\
	lib/arm/libnpth_xasan.so\
	lib/arm/libnslinker.so\
	lib/arm/libonetex.so\
	lib/arm/libosfix.so\
	lib/arm/libpangleflipped.so\
	lib/arm/libperception_ml.so\
	lib/arm/libpl_droidsonroids_gif.so\
	lib/arm/libpreload.so\
	lib/arm/libprofiler.so\
	lib/arm/libpush_ka.so\
	lib/arm/libqmiVsyncHook.so\
	lib/arm/libquick.so\
	lib/arm/libreflect.so\
	lib/arm/librelax.so\
	lib/arm/librelaxui.so\
	lib/arm/libreparo.so\
	lib/arm/libresources.so\
	lib/arm/libropaencrypt.so\
	lib/arm/libscalpel_unw.so\
	lib/arm/libserval_svg.so\
	lib/arm/libsgmain.so\
	lib/arm/libshadowhook.so\
	lib/arm/libsheo.so\
	lib/arm/libskity-graphics.so\
	lib/arm/libskity.so\
	lib/arm/libsniper_record.so\
	lib/arm/libsoloader.so\
	lib/arm/libsoloadmonitor.so\
	lib/arm/libspeechengine.so\
	lib/arm/libsscronet.so\
	lib/arm/libstatic-webp.so\
	lib/arm/libstoragehandlerlib.so\
	lib/arm/libstretch.so\
	lib/arm/libsweep_tools.so\
	lib/arm/libsys-platform.so\
	lib/arm/libsysmonitor.so\
	lib/arm/libsysoptimizer.so\
	lib/arm/libtailor.so\
	lib/arm/libtexturerender_native.so\
	lib/arm/libtnet-3.1.14.so\
	lib/arm/libtraceroute-lib.so\
	lib/arm/libttboringssl.so\
	lib/arm/libttcrypto.so\
	lib/arm/libttffmpeg.so\
	lib/arm/libttheif_dec.so\
	lib/arm/libttheif_enc.so\
	lib/arm/libttmaudioprocess.so\
	lib/arm/libttmpaflns.so\
	lib/arm/libttmplayer.so\
	lib/arm/libttmverify.so\
	lib/arm/libttmverifylite.so\
	lib/arm/libtttext_dyreader.so\
	lib/arm/libtttext_lite.so\
	lib/arm/libttvesdk.so\
	lib/arm/libturbo.so\
	lib/arm/libumeng-spy.so\
	lib/arm/libundead_native_ability_q.so\
	lib/arm/libunicorn-main.so\
	lib/arm/libunicorn.so\
	lib/arm/libutility.so\
	lib/arm/libvcbasekit.so\
	lib/arm/libvcn.so\
	lib/arm/libvcnverify.so\
	lib/arm/libvcnverifylite.so\
	lib/arm/libvctfo.so\
	lib/arm/libvideodec.so\
	lib/arm/libvoip.so\
	lib/arm/libvolcenginertc.so\
	lib/arm/libwasm.so\
	lib/arm/libwatson.so\
	lib/arm/libwcdb.so\
	lib/arm/libwcdb2.so\
	lib/arm/libweibosdkcore.so\
	lib/arm/libwhisper.so\
	lib/arm/libwind.so\
	lib/arm/libworker.so\
	lib/arm/libwppatch.so\
	lib/arm/libyoga.so\
	lib/arm/libyuv.so\
	lib/arm/libzaid.so\
	lib/arm/libzeus_direct_dex.so\
	lib/arm/libzootopia.so\

MY_APP_LIB_PATH := $(TARGET_OUT_ODM)/bundled_uninstall_back-app/$(LOCAL_MODULE)/lib/$(LOCAL_JNI_SHARED_LIBRARIES_ABI)
ifneq ($(LOCAL_JNI_SHARED_LIBRARIES_ABI), None)
$(warning MY_APP_LIB_PATH=$(MY_APP_LIB_PATH))
LOCAL_POST_INSTALL_CMD :=     mkdir -p $(MY_APP_LIB_PATH)     $(foreach lib, $(MY_LOCAL_PREBUILT_JNI_LIBS), ; cp -f $(LOCAL_PATH)/$(lib) $(MY_APP_LIB_PATH)/$(notdir $(lib)))
endif
include $(BUILD_PREBUILT)

